INSERT INTO genres (name) VALUES ('rock')
INSERT INTO genres (name) VALUES ('jazz')
INSERT INTO genres (name) VALUES ('pop')
INSERT INTO genres (name) VALUES ('reggae')
INSERT INTO genres (name) VALUES ('hip hop')


INSERT INTO performers (nickname) VALUES ('Sting')
INSERT INTO performers (nickname) VALUES ('Louis Armstrong')
INSERT INTO performers (nickname) VALUES ('Eminem')
INSERT INTO performers (nickname) VALUES ('Paul McCartney')
INSERT INTO performers (nickname) VALUES ('Michael Jackson')
INSERT INTO performers (nickname) VALUES ('Bob Marley')
INSERT INTO performers (nickname) VALUES ('Freddie Mercury')
INSERT INTO performers (nickname) VALUES ('Shakira ')


INSERT INTO albums (name,  album_release_year) VALUES ('Bad', '07.09.1987')
INSERT INTO albums (name,  album_release_year) VALUES ('Laundry Service', '13.11.2001')
INSERT INTO albums (name,  album_release_year) VALUES ('Infinite', '12.11.1996')
INSERT INTO albums (name,  album_release_year) VALUES ('Soul Rebels', '01.12.1970')
INSERT INTO albums (name,  album_release_year) VALUES ('All the Best!', '02.11.1987')
INSERT INTO albums (name,  album_release_year) VALUES ('Recovery', '21.06.2010')
INSERT INTO albums (name,  album_release_year) VALUES ('The Dream of the Blue Turtles', '01.06.1985')
INSERT INTO albums (name,  album_release_year) VALUES ('What a Wonderful World', '01.01.1968')
INSERT INTO albums (name,  album_release_year) VALUES ('Kamikaze', '31.08.2018')
INSERT INTO albums (name,  album_release_year) VALUES ('Music to Be Murdered By', '17.01.2020')


INSERT INTO tracks (name, length, album_id) VALUES ('Infinite', '4:01', '3')
INSERT INTO tracks (name, length, album_id) VALUES ('Underneath Your Clothes', '3:45', '2')
INSERT INTO tracks (name, length, album_id) VALUES ('Liberian Girl', '3:55', '1')
INSERT INTO tracks (name, length, album_id) VALUES ('Dirty Diana', '4:42', '1')
INSERT INTO tracks (name, length, album_id) VALUES ('What a Wonderful World', '4:19', '8')
INSERT INTO tracks (name, length, album_id) VALUES ('Soul Rebel', '3:22', '4')
INSERT INTO tracks (name, length, album_id) VALUES ('Its Alright', '2:39', '4')
INSERT INTO tracks (name, length, album_id) VALUES ('Jet', '4:08', '5')
INSERT INTO tracks (name, length, album_id) VALUES ('Silly Love Songs', '5:54', '5')
INSERT INTO tracks (name, length, album_id) VALUES ('Pipes of Peace', '3:25', '5')
INSERT INTO tracks (name, length, album_id) VALUES ('Not Afraid', '4:08', '6')
INSERT INTO tracks (name, length, album_id) VALUES ('No Love', '5:00', '6')
INSERT INTO tracks (name, length, album_id) VALUES ('Russians', '3:57', '7')
INSERT INTO tracks (name, length, album_id) VALUES ('Love Is the Seventh Wave', '3:30', '7')
INSERT INTO tracks (name, length, album_id) VALUES ('If You Love Somebody Set Them Free', '4:14', '7')
INSERT INTO tracks (name, length, album_id) VALUES ('My Cup', '3:39', '4')
INSERT INTO tracks (name, length, album_id) VALUES ('Lucky You', '4:04', '9')
INSERT INTO tracks (name, length, album_id) VALUES ('Darkness', '5:37', '10')
INSERT INTO tracks (name, length, album_id) VALUES ('Godzilla', '3:31', '10')


INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Calm', '01.01.2020')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Dance Mix', '01.01.2015')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Hits', '01.01.2022')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Pop 2000', '01.01.2020')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Lovely', '01.01.2022')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Relax', '01.01.2017')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Foreign', '01.01.1990')
INSERT INTO mix_tapes (name, mix_tape_release_year) VALUES ('Top5', '01.01.2021')


INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (1, 3)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (1, 5)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (1, 14)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (2, 2)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (2, 6)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (2, 8)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 2)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 3)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 7)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 11)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 12)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 13)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (3, 5)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (4, 2)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (4, 11)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (5, 3)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (5, 4)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (5, 14)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (6, 2)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (6, 5)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (6, 6)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 3)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 4)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 5)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 6)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 7)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 8)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 9)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 10)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 13)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 14)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (7, 15)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (8, 3)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (8, 6)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (8, 7)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (8, 11)
INSERT INTO tracks_in_a_mix_tape (mix_tapes_id, track_id) VALUES (8, 15)


INSERT INTO performers_genres (performer_id, genre_id) VALUES (2, 1)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (2, 3)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (2, 4)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (2, 2)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (3, 2)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (4, 5)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (5, 1)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (5, 3)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (6, 3)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (6, 1)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (7, 4)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (8, 1)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (8, 3)
INSERT INTO performers_genres (performer_id, genre_id) VALUES (9, 3)




INSERT INTO performers_albums (album_id, performer_id) VALUES (1, 6)
INSERT INTO performers_albums (album_id, performer_id) VALUES (2, 9)
INSERT INTO performers_albums (album_id, performer_id) VALUES (3, 4)
INSERT INTO performers_albums (album_id, performer_id) VALUES (4, 7)
INSERT INTO performers_albums (album_id, performer_id) VALUES (5, 5)
INSERT INTO performers_albums (album_id, performer_id) VALUES (6, 4)
INSERT INTO performers_albums (album_id, performer_id) VALUES (7, 2)
INSERT INTO performers_albums (album_id, performer_id) VALUES (8, 3)
INSERT INTO performers_albums (album_id, performer_id) VALUES (9, 4)
INSERT INTO performers_albums (album_id, performer_id) VALUES (10, 4)









